title: "Skybound"
title_link: ""
artist: "Meebah"
artist_link: "https://www.youtube.com/@meebahmusic5835"
album: ""
album_link: ""
year: 2024
bpm: 140
preview_start: 35000
charted_by: "liqMix"
charted_by_link: "https://liq.mx"
version: "0.0.2"