title: "Torpid Orchid"
title_link: "https://smokingmirrors.bandcamp.com/track/torpid-orchid"
artist: "Hypnogram"
artist_link: "https://hypnogram.angelfire.com/"
album: "Eye"
album_link: "https://smokingmirrors.bandcamp.com/album/eye"
year: 2016
bpm: 120
preview_start: 16600
charted_by: "liqMix"
charted_by_link: "https://github.com/liqMix"
version: "1.0.0"