title: "uma ame"
title_link: ""
artist: "liqMix"
artist_link: ""
album: ""
album_link: ""
year: 2024
bpm: 146
preview_start: 130000
charted_by: "liqMix"
charted_by_link: "https://github.com/liqMix"
version: "0.0.1"