title: "galactical"
title_link: ""
artist: "liqMix"
artist_link: ""
album: ""
album_link: ""
year: 2024
bpm: 100
preview_start: 35000
charted_by: "liqMix"
charted_by_link: "https://liq.mx"
version: "0.0.1"