services:
  db:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=holiday_db
      - POSTGRES_HOST_AUTH_METHOD=md5
    ports:
      - '5435:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=500'
      - '-c'
      - 'shared_buffers=256MB'
      - '-c'
      - 'work_mem=16MB'
      - '-c'
      - 'maintenance_work_mem=256MB'
      - '-c'
      - 'log_statement=mod'  # Only log modifications
      - '-c'
      - 'log_destination=stderr'

volumes:
  postgres_data: