title: "beppuSLAP!"
title_link: ""
artist: "liqMix"
artist_link: ""
album: "slapTrax"
album_link: ""
year: 2024
bpm: 99
preview_start: 0
charted_by: "liqMix"
charted_by_link: "https://github.com/liqMix"
version: "1.0.0"