title: "4est"
title_link: ""
artist: "liqMix"
artist_link: ""
album: "slapTrax"
album_link: ""
year: 2024
bpm: 130
preview_start: 28000
charted_by: "liqMix"
charted_by_link: "https://github.com/liqMix"
version: "1.0.0"