name: Build Executables
on: [push]
jobs:

  build-win:
    name: Build Windows binary
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'
    - name: Build Windows exe
      working-directory: cmd/game
      shell: bash
      run: go build -o ../../ebihack24.exe
    - name: Upload Windows exe
      uses: actions/upload-artifact@v3
      with:
        name: ebihack24-win
        path: |
          LICENSE
          ebihack24.exe

  build-mac:
    name: Build MacOS binary
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'
    - name: Build Mac exe
      working-directory: cmd/game
      shell: bash
      run: go build -o ../../ebihack24
    - name: Tar it up
      shell: bash
      run: tar -zcvf ebihack24-mac.tar.gz ebihack24 LICENSE
    - name: Upload Mac exe
      uses: actions/upload-artifact@v3
      with:
        name: ebihack24-mac
        path: ebihack24-mac.tar.gz

  build-lin:
    name: Build Linux binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'
    - name: Install dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get -y install libgl1-mesa-dev xorg-dev libasound2-dev
    - name: Build Linux exe
      working-directory: cmd/game
      shell: bash
      run: go build -o ../../ebihack24
    - name: Tar it up
      shell: bash
      run: tar -zcvf ebihack24-lin.tar.gz ebihack24 LICENSE
    - name: Upload Linux exe
      uses: actions/upload-artifact@v3
      with:
        name: ebihack24-lin
        path: ebihack24-lin.tar.gz

  build-web:
    name: Build Web binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'
    - name: Build Web binary
      working-directory: cmd/game
      shell: bash
      run: GOOS=js GOARCH=wasm go build -o ../../web/ebihack24.wasm
    - name: Copy WASM exec script
      shell: bash
      run: cp $(go env GOROOT)/misc/wasm/wasm_exec.js web/.
    - name: Upload Web build
      uses: actions/upload-artifact@v3
      with:
        name: ebihack24-web
        path: |
          web/
          LICENSE

  upload-bundle:
    name: Bundle binaries with dev assets
    runs-on: ubuntu-latest
    needs: [build-lin, build-mac, build-win]
    steps:
    - uses: actions/checkout@v3
    - name: Download Windows binary
      uses: actions/download-artifact@v3
      with:
        name: ebihack24-win
    - name: Download Linux binary
      uses: actions/download-artifact@v3
      with:
        name: ebihack24-lin
    - name: Download Mac binary
      uses: actions/download-artifact@v3
      with:
        name: ebihack24-mac
    - name: Upload beta testing bundle
      uses: actions/upload-artifact@v3
      with:
        name: ebihack24-bundle
        path: |
          README.md
          LICENSE
          ebihack24-lin.tar.gz
          ebihack24-mac.tar.gz
          ebihack24.exe


