name: Build WASM and Deploy to Pages

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'
      - name: Build Web binary
        working-directory: cmd/game
        shell: bash
        run: GOOS=js GOARCH=wasm go build -o ../../web/ebihack24.wasm
      - name: Copy WASM exec script
        shell: bash
        run: cp $(go env GOROOT)/misc/wasm/wasm_exec.js web/.
      - name: Upload Web build
        uses: actions/upload-artifact@v3
        with:
          name: ebihack24--web
          path: |
            web/
            LICENSE.md
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./web"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
