title: "Furor"
title_link: ""
artist: "Meebah"
artist_link: "https://www.youtube.com/@meebahmusic5835"
album: "Meebah"
album_link: ""
year: 2024
bpm: 80
preview_start: 35000
charted_by: "liqMix"
charted_by_link: "https://github.com/liqMix"
version: "1.0.0"